do_merge: Force a rebuild every N trees
Currently we ensure we are building periodically by flagging certain trees
as being essential to build. While some of the trees are important to build
(eg, the final tree merged into fixes) some of this is just to ensure that
we are building often enough that build failures are easy to track down.
This can result in annoyances like having a build failure shortly before
one of these explicitly flagged trees. Instead start tracking the set of
trees that we merged without triggering builds for and trigger a build when
that passes a certain number, currently hard coded to 50 but that should be
configurable more sensibly.

As part of this refactor the checks for needing a build to be a bit more
linear.

Signed-off-by: Mark Brown <broonie@kernel.org>

diff --git a/do_merge b/do_merge
--- a/do_merge
+++ b/do_merge
@@ -30,6 +30,8 @@ tools_dir=$(dirname "$0")
 . "$tools_dir/common.sh"
 . "$tools_dir/check_dups.sh"
 
+touch ../unbuilt
+
 log()
 {
 	echo "$@" | tee -a "$LOG_FILE"
@@ -200,20 +202,27 @@ for h in $heads; do
 		continue
 	fi
 
-	if ! $need_build; then
-		# See if we need to build after merging this tree
-		if [ -n "$(git diff "$old_head"..)" ]; then
-			need_build=true
-		fi
+	# See if we need to build after merging this tree
+	if [ "$(get_build_flag "$tree")" != "yes" ]; then
+		need_build=true
 	fi
+	if ! [ -f "$top_dir/old-versions/$tree" ]; then
+		need_build=true
+	fi
+
+	# Ensure we build periodically so we're not lost on failure
+	if [ $(wc -l ../unbuilt | cut -f1 -d\ ) -gt 50 ]; then
+		need_build=true
+	fi
+
 	if ! $need_build; then
+		echo ${tree} >> ../unbuilt
 		continue
 	fi
 
-	if [ "$(get_build_flag "$tree")" != "yes" ]; then
-		if ! [ -f "$top_dir/old-versions/$tree" ]; then
-			continue
-		fi
+	# Special case, skip trees unchanged since the last time
+	if [ -n "$(git diff "$old_head"..)" ]; then
+		continue
 	fi
 
 	repo="${build_host:+$build_host:}${build_dir}"
@@ -231,6 +240,10 @@ for h in $heads; do
 	fi
 
 	rm -f "$top_dir/old-versions/$tree"
+	if [ -f ../unbuilt ]; then
+		rm ../unbuilt
+		touch ../unbuilt
+	fi
 
 	need_build=false
 done
